mu_set = (1,2,3,4,5,6,7,8)
My_set = (6.7,5,"string",False)
print(mu_set)
print(My_set)
me_set = set([1,2,3,2])
print(me_set,"\n")
num_set = set([0,1,3,4,5])
print("Orignal set:")
print(num_set)
num_set.pop()
print("After remooving the first element from the said set:")
print(num_set, "\n")